spring.application.name=notification-service

server.port=8084

spring.datasource.url=jdbc:postgresql://localhost:5439/notificationdb
spring.datasource.username=notif_admin
spring.datasource.password=notif_pass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

jwt.secret=homeservices_secret_key_must_be_very_long_for_security_1234567890
jwt.expiration=86400000